language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO="Django>=1.7,<1.8" DB=sqlite
  - DJANGO="Django>=1.7,<1.8" DB=postgres
  - DJANGO="Django>=1.7,<1.8" DB=mysql
  - DJANGO="Django>=1.8,<1.9" DB=sqlite
  - DJANGO="Django>=1.8,<1.9" DB=postgres
  - DJANGO="Django>=1.8,<1.9" DB=mysql
  - DJANGO="Django>=1.9,<1.10" DB=sqlite
  - DJANGO="Django>=1.9,<1.10" DB=postgres
  - DJANGO="Django>=1.9,<1.10" DB=mysql
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="Django>=1.9,<1.10" DB=sqlite
    - python: "3.3"
      env: DJANGO="Django>=1.9,<1.10" DB=postgres
    - python: "3.3"
      env: DJANGO="Django>=1.9,<1.10" DB=mysql

    - python: "3.5"
      env: DJANGO="Django>=1.7,<1.8" DB=sqlite
    - python: "3.5"
      env: DJANGO="Django>=1.7,<1.8" DB=postgres
    - python: "3.5"
      env: DJANGO="Django>=1.7,<1.8" DB=mysql
before_script:
  - mysql -e 'create database pybbm;'
  - psql -c 'create database pybbm;' -U postgres
install:
  - if [[ $DB == mysql ]]; then pip install -qU mysqlclient; fi
  - if [[ $DB == postgres ]]; then pip install -qU psycopg2; fi
  - pip install -qU $DJANGO
  - CFLAGS="-O0" pip install -qU -r test/test_project/requirements_test.txt
script:
  - python setup.py test
