language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO=1.4.10 DB=sqlite
  - DJANGO=1.4.10 DB=postgres
  - DJANGO=1.4.10 DB=mysql
  - DJANGO=1.5.5 DB=sqlite
  - DJANGO=1.5.5 DB=postgres
  - DJANGO=1.5.5 DB=mysql
  - DJANGO=1.6.2 DB=sqlite
  - DJANGO=1.6.2 DB=postgres
  - DJANGO=1.6.2 DB=mysql
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO=1.4.10 DB=sqlite
    - python: "3.2"
      env: DJANGO=1.4.10 DB=postgres
    - python: "3.2"
      env: DJANGO=1.4.10 DB=mysql
    - python: "3.3"
      env: DJANGO=1.4.10 DB=sqlite
    - python: "3.3"
      env: DJANGO=1.4.10 DB=postgres
    - python: "3.3"
      env: DJANGO=1.4.10 DB=mysql

    - python: "3.2"
      env: DJANGO=1.5.5 DB=mysql
    - python: "3.3"
      env: DJANGO=1.5.5 DB=mysql
    - python: "3.2"
      env: DJANGO=1.6.2 DB=mysql
    - python: "3.3"
      env: DJANGO=1.6.2 DB=mysql
before_script:
  - mysql -e 'create database pybbm;'
  - psql -c 'create database pybbm;' -U postgres
install:
  - if [[ $DB == mysql ]]; then pip install -q mysql-python --use-mirrors; fi
  - if [[ $DB == postgres ]]; then pip install -q psycopg2 --use-mirrors; fi
  - pip install Django==$DJANGO --use-mirrors
  - pip install Pillow -U
  - pip install South -U
  - pip install -r test/test_project/requirements_test.txt
script:
  - python setup.py test

